/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Search result returned from xgrep. */
export interface SearchResult {
  /** File path relative to root. */
  file: string
  /** Line number (1-based). */
  lineNumber: number
  /** The matching line content. */
  line: string
}
/** Search options for xgrep. */
export interface SearchOptions {
  /** Case-insensitive search (ASCII-only). */
  caseInsensitive?: boolean
  /** Treat pattern as regex. */
  regex?: boolean
  /** Filter by file type (e.g., "rs", "py", "js"). */
  fileType?: string
  /** Maximum number of results. */
  maxCount?: number
  /** Only search git-changed files. */
  changedOnly?: boolean
  /** Search files changed within duration (e.g., "1h", "2d"). */
  since?: string
  /** Filter by path substring. */
  pathPattern?: string
  /** Check index freshness before searching. */
  fresh?: boolean
  /**
   * Match only at word boundaries (wraps the pattern in `(?:...)`).
   * Enabling this always runs the regex engine, even for literal patterns.
   */
  word?: boolean
  /**
   * Include/exclude result paths by glob (ripgrep -g compatible).
   * Prefix a glob with `!` to exclude. Empty/omitted = no filtering.
   */
  globs?: Array<string>
}
/** Index status returned from xgrep. */
export interface IndexStatus {
  /** Freshness state: "fresh", "stale", or "missing". */
  state: string
  /** Number of files changed since the last build. Present only when state is "stale". */
  changedFiles?: number
  /** Number of files in the index (0 if missing). */
  indexedFiles: number
  /** Index file size in bytes (0 if missing). */
  indexSizeBytes: number
  /** Path to the index file. */
  indexPath: string
}
/** Ultra-fast indexed code search engine. */
export declare class Xgrep {
  /** Open a directory for searching. Index location is auto-resolved. */
  static open(root: string): Xgrep
  /** Open a directory with local index storage (.xgrep/ in the project root). */
  static openLocal(root: string): Xgrep
  /** Build or rebuild the search index. */
  buildIndex(): void
  /** Search for a pattern in the indexed codebase. */
  search(pattern: string, opts?: SearchOptions | undefined | null): Array<SearchResult>
  /** Get the current index status as a structured object. */
  indexStatus(): IndexStatus
  /** Get the root directory path. */
  get root(): string
  /** Get the index file path. */
  get indexPath(): string
}
