/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Search result returned from xgrep. */
export interface SearchResult {
  /** File path relative to root. */
  file: string
  /** Line number (1-based). */
  lineNumber: number
  /** The matching line content. */
  line: string
}
/** Search options for xgrep. */
export interface SearchOptions {
  /** Case-insensitive search (ASCII-only). */
  caseInsensitive?: boolean
  /** Treat pattern as regex. */
  regex?: boolean
  /** Filter by file type (e.g., "rs", "py", "js"). */
  fileType?: string
  /** Maximum number of results. */
  maxCount?: number
  /** Only search git-changed files. */
  changedOnly?: boolean
  /** Search files changed within duration (e.g., "1h", "2d"). */
  since?: string
  /** Filter by path substring. */
  pathPattern?: string
  /** Check index freshness before searching. */
  fresh?: boolean
}
/** Ultra-fast indexed code search engine. */
export declare class Xgrep {
  /** Open a directory for searching. Index location is auto-resolved. */
  static open(root: string): Xgrep
  /** Open a directory with local index storage (.xgrep/ in the project root). */
  static openLocal(root: string): Xgrep
  /** Build or rebuild the search index. */
  buildIndex(): void
  /** Search for a pattern in the indexed codebase. */
  search(pattern: string, opts?: SearchOptions | undefined | null): Array<SearchResult>
  /** Get the current index status. */
  indexStatus(): string
  /** Get the root directory path. */
  get root(): string
  /** Get the index file path. */
  get indexPath(): string
}
